### PR TITLE
Started work on DiabloUI.dll

### PR DESCRIPTION
**Pull request by aleaksah**
Hello.
I started work on DiabloUI.dll, but I don't sure I finish that. So, let this files be here, maybe they help somebody.

### CODE REVIEW

**Comment by mewmew** [comment]
@aleaksah Thanks for the PR! It seems you included the IDB database in the PR. As this file contains the original assembly, we cannot upload it to the notes repo, as that would violate copyright. The purpose of this repo is purely documentation.

The create_declarations scripts are useful, however. So, remove the IDB file before we can merge. Also, consider placing these scripts in the [_scripts_](https://github.com/sanctuary/notes/tree/master/_scripts_) subdirectory.

E.g.
- `_scripts_/diabloui`
- `_scripts_/storm`

Cheers,
/u

**Comment by mewmew** [comment]
*ping* @aleaksah

**Comment by aleaksah** [comment]
Sorry, I was busy.
I don't think that .IDB contains full image, but if you think so - I fix this commit.
Also, is there any documentation for Storm.dll?

**Comment by mewmew** [comment]
>  I don't think that .IDB contains full image, but if you think so - I fix this commit.

Please do. I believe you can open the .IDB database with IDA even if you don't have the original file, and seeing as IDA contains a full assembly listing, it contains in essence a copy of the original binary.

>  Also, is there any documentation for Storm.dll?

I think the storm library has been reversed by Ladislav Zezula: https://github.com/ladislav-zezula/StormLib

I'm not sure which exact version however, or if it is the storm.dll library used by Diablo 1 or some other game from Blizzard.

**Comment by aleaksah** [comment]
Ok, files moved.
>I think the storm library has been reversed by Ladislav Zezula: https://github.com/ladislav-zezula/StormLib
This project implements only work with MPQ archives, while Storm.dll have many other functions.

**Comment by mewmew** [comment]
Thanks Aleksandr! Merging the PR.

In the future, I think these scripts will be converted to header files, to follow the same convention as taken to document Diablo.exe.

The benefit with having them in header files is that they become searchable through:
http://sanctuary.github.io/notes

Also, the Scripture tool allows generation of IDC scripts to facilitate importing the variable names into IDA; e.g.
http://sanctuary.github.io/notes/notes.idc

> This project implements only work with MPQ archives, while Storm.dll have many other functions.

Some preliminary work for Storm documentation has been done at https://github.com/sanctuary/notes/blob/master/storm.md

For full reversing, you'd have to refer to @galaxyhaxz as the notes repo is only intended for documentation and not full reversal.

**Comment by mewmew** [comment]
> Actually, I'm not going to reverse DiabloUI for the reason that it relies heavily on the Storm Library. The actual base game rarely uses Storm except in cases of multiplayer, so it shouldn't be that hard to eliminate the dependency.

Sounds good. As long as we can replicate the behaviour, it should be possible to get rid of the diabloui.dll dependency altogether.

> Instead, I'm working on a spreadsheet to give us the entire layout between game versions. We could build upon the script you wrote to plug everything into a .IDB so we don't have to distribute them. This will make reversing other versions much faster as well. So keep up the good work!

Indeed. Making IDA databases Git:able is great! For the IDC generation tool, @Predelnik is to thank.

**Pull request merged**
